### ISSUE TITLE
 An error (1332) occurred while enumerating the group membership.  The member's SID could not be resolved. 

### ISSUE THREAD

**Issue by ryannewington** [lithnet/miis-autosync#103]
During installation, the user may be prompted with an error message when trying to add the service account to the fim sync admins group

```
An error (1332) occurred while enumerating the group membership.  The member's SID could not be resolved. 
```

This is caused by a bug in the .NET framework, which causes an exception when the group contains a member that no longer exists in the directory. This is represented in the group member UI as a group member that appears by its SID, rather than display name.

Removing the orphaned object from the group works around the issue and allows the installer to proceed.

**Comment by ryannewington** [comment]
```
ystem.DirectoryServices.AccountManagement.PrincipalOperationException: An error (1332) occurred while enumerating the group membership.  The member's SID could not be resolved.
   at System.DirectoryServices.AccountManagement.SAMMembersSet.IsLocalMember(Byte sid)
   at System.DirectoryServices.AccountManagement.SAMMembersSet.MoveNextLocal()
   at System.DirectoryServices.AccountManagement.SAMMembersSet.MoveNext()
   at System.DirectoryServices.AccountManagement.PrincipalCollectionEnumerator.MoveNext()
   at System.DirectoryServices.AccountManagement.PrincipalCollection.ContainsEnumTest(Principal principal)
   at System.DirectoryServices.AccountManagement.PrincipalCollection.Contains(Principal principal)
   at Lithnet.Miiserver.AutoSync.Setup.CustomActions.CustomActions.AddUserToGroup(String account, String groupSid)
   at Lithnet.Miiserver.AutoSync.Setup.CustomActions.CustomActions.AddServiceAccountToFimSyncAdmins(Session session)
```

**Comment by ryannewington** [comment]
https://stackoverflow.com/questions/13050428/how-to-overcome-the-the-members-sid-could-not-be-resolved-error-when-checking

**Comment by ryannewington** [comment]
Fixed in https://github.com/lithnet/miis-autosync/releases/tag/v1.1.6500
