### ISSUE TITLE
"The controller encountered an unrecoverable error" when stopping a controller or cancelling a job

### ISSUE THREAD

**Issue by ryannewington** [lithnet/miis-autosync#129]
```
ACMA: The controller encountered a unrecoverable error
System.Threading.SemaphoreFullException: Adding the specified count to the semaphore would cause it to exceed its maximum count.
   at System.Threading.SemaphoreSlim.Release(Int32 releaseCount)
   at Lithnet.Miiserver.AutoSync.MAController.ReleaseLock(SemaphoreSlim mre, String name, String caller)
   at Lithnet.Miiserver.AutoSync.MAController.TakeLocksAndExecute(ExecutionParameters action)
   at Lithnet.Miiserver.AutoSync.MAController.Init()
   at Lithnet.Miiserver.AutoSync.MAController.<Start>b__110_0()
```

**Comment by ryannewington** [comment]
Fixed in https://github.com/lithnet/miis-autosync/releases/tag/v1.2.6692
