### ISSUE TITLE
AutoSync unrecoverable error

### ISSUE THREAD

**Issue by StevieNookz** [lithnet/miis-autosync#167]
Hi,

Autosync is logging an unrecoverable error when trying to trigger an export run for one of my connectors.  There really isn't much to gather from the logs:

2019-08-09 04:59:06.6927|ERROR|qdjag.onmicrosoft.com - MSGraphPS: The controller encountered a unrecoverable errorSystem.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Lithnet.Miiserver.AutoSync.MAController.IsSyncStep(String runProfileName)
   at Lithnet.Miiserver.AutoSync.MAController.SetExclusiveMode(ExecutionParameters action)
   at Lithnet.Miiserver.AutoSync.MAController.Init()
   at Lithnet.Miiserver.AutoSync.MAController.<Start>b__120_0()

Can you assist?

Thanks, Steve.

**Comment by StevieNookz** [comment]
![image](https://user-images.githubusercontent.com/43834248/62747086-26c7cd80-ba96-11e9-88d7-b18b01d9d8d0.png)

**Comment by ryannewington** [comment]
@StevieNookz,

Have any run profiles been added, renamed or deleted since the autosync service started? You may need to stop and restart autosync (the service itself running on windows, not just the controller in the app), if you have made changes to run profiles to pick up the changes.

Ryan

**Comment by StevieNookz** [comment]
Yes, that was it.  Feel like a clown now :)  Thanks.
