### ISSUE TITLE
An error occurred clearing the run history

### ISSUE THREAD

**Issue by mwwessie** [lithnet/miis-autosync#184]
We have enabled Clear Run History as shown below:
<img width="725" alt="image" src="https://github.com/lithnet/miis-autosync/assets/27192287/3efc3354-0484-4034-98a6-9fabc1c5b9ec">

We recieve the following error in the Event Viewer:
<img width="533" alt="image" src="https://github.com/lithnet/miis-autosync/assets/27192287/341aaddb-5386-4c69-9007-7fd321cc9497">

I can see in the following in the log file:

```
2023-11-10 02:15:33.8571| INFO|Clearing run history older than 7.00:00:00
2023-11-10 02:15:34.4665|TRACE|Timer elapsed. Next event at 10/11/2023 2:30:34 AM

2023-11-10 02:16:04.2669|ERROR|An error occurred clearing the run historySystem.NullReferenceException: Object reference not set to an instance of an object.
   at Lithnet.Miiserver.Client.SyncServer.SaveRunHistory(DateTime beforeDate, String filename)
   at Lithnet.Miiserver.Client.SyncServer.ClearRunHistory(DateTime clearBeforeDate, String filename)
   at Lithnet.Miiserver.AutoSync.Program.ClearRunHistory()

2023-11-10 10:15:33.8436| INFO|Clearing run history older than 7.00:00:00
2023-11-10 10:15:34.7186|TRACE|Timer elapsed. Next event at 10/11/2023 10:30:34 AM

2023-11-10 10:16:06.5875|ERROR|An error occurred clearing the run historySystem.NullReferenceException: Object reference not set to an instance of an object.
   at Lithnet.Miiserver.Client.SyncServer.SaveRunHistory(DateTime beforeDate, String filename)
   at Lithnet.Miiserver.Client.SyncServer.ClearRunHistory(DateTime clearBeforeDate, String filename)
   at Lithnet.Miiserver.AutoSync.Program.ClearRunHistory()
``` 

The Lithnet service account got full permissions to the folder as it's writing the log files to this directory as well.

When I uncheck "Save run history before clearing", it clears the history without any issues.

Is there anything else I must configure to be able to save the history?

Regards,
André

**Comment by ryannewington** [comment]
@mwwessie 

That's a bit strange. It sounds like there might be a run history item that is corrupted. Do you get any similar error when clear/savings the runs in the sync service itself?

Can you let me know the version of `Lithnet.Miiserver.Client.dll` found in the Lithnet AutoSync program files folder?

**Comment by mwwessie** [comment]
Thanks, Ryan

I'll check for you as soon as I can as I'll be off for the next 2 weeks.

Regards,
André

________________________________
